/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Plant Tracking API
 * Backend API for plant tracking home page
 * OpenAPI spec version: 0.1.0
 */
export interface BodyCreateMediaAttachmentApiMediaMediaAttachmentsPost {
  plant_id: string;
  media_type: string;
  label?: string | null;
  tags?: string | null;
  file: Blob;
}

export interface BodyGetMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGet {
  expiration?: number;
}

export interface BodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut {
  label?: string | null;
  tags?: string | null;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type healthCheckHealthGetResponse200 = {
  data: unknown
  status: 200
}

export type healthCheckHealthGetResponseSuccess = (healthCheckHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthCheckHealthGetResponse = (healthCheckHealthGetResponseSuccess)

export const getHealthCheckHealthGetUrl = () => {




  return `/health`
}

/**
 * Health check endpoint.
 * @summary Health Check
 */
export const healthCheckHealthGet = async ( options?: RequestInit): Promise<healthCheckHealthGetResponse> => {

  const res = await fetch(getHealthCheckHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthCheckHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthCheckHealthGetResponse
}



export type rootGetResponse200 = {
  data: unknown
  status: 200
}

export type rootGetResponseSuccess = (rootGetResponse200) & {
  headers: Headers;
};
;

export type rootGetResponse = (rootGetResponseSuccess)

export const getRootGetUrl = () => {




  return `/`
}

/**
 * Root endpoint.
 * @summary Root
 */
export const rootGet = async ( options?: RequestInit): Promise<rootGetResponse> => {

  const res = await fetch(getRootGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rootGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rootGetResponse
}



export type getPlantsNeedingCareApiPlantsCareNeededGetResponse200 = {
  data: unknown
  status: 200
}

export type getPlantsNeedingCareApiPlantsCareNeededGetResponseSuccess = (getPlantsNeedingCareApiPlantsCareNeededGetResponse200) & {
  headers: Headers;
};
;

export type getPlantsNeedingCareApiPlantsCareNeededGetResponse = (getPlantsNeedingCareApiPlantsCareNeededGetResponseSuccess)

export const getGetPlantsNeedingCareApiPlantsCareNeededGetUrl = () => {




  return `/api/plants/care-needed`
}

/**
 * Get plants needing care attention today.
 *
 * Returns mock data or empty response until care threshold logic is defined.
 * @summary Get Plants Needing Care
 */
export const getPlantsNeedingCareApiPlantsCareNeededGet = async ( options?: RequestInit): Promise<getPlantsNeedingCareApiPlantsCareNeededGetResponse> => {

  const res = await fetch(getGetPlantsNeedingCareApiPlantsCareNeededGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPlantsNeedingCareApiPlantsCareNeededGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPlantsNeedingCareApiPlantsCareNeededGetResponse
}



export type createMediaAttachmentApiMediaMediaAttachmentsPostResponse200 = {
  data: unknown
  status: 200
}

export type createMediaAttachmentApiMediaMediaAttachmentsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createMediaAttachmentApiMediaMediaAttachmentsPostResponseSuccess = (createMediaAttachmentApiMediaMediaAttachmentsPostResponse200) & {
  headers: Headers;
};
export type createMediaAttachmentApiMediaMediaAttachmentsPostResponseError = (createMediaAttachmentApiMediaMediaAttachmentsPostResponse422) & {
  headers: Headers;
};

export type createMediaAttachmentApiMediaMediaAttachmentsPostResponse = (createMediaAttachmentApiMediaMediaAttachmentsPostResponseSuccess | createMediaAttachmentApiMediaMediaAttachmentsPostResponseError)

export const getCreateMediaAttachmentApiMediaMediaAttachmentsPostUrl = () => {




  return `/api/media/media-attachments/`
}

/**
 * Create a new media attachment.
 * @summary Create Media Attachment
 */
export const createMediaAttachmentApiMediaMediaAttachmentsPost = async (bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost: BodyCreateMediaAttachmentApiMediaMediaAttachmentsPost, options?: RequestInit): Promise<createMediaAttachmentApiMediaMediaAttachmentsPostResponse> => {
    const formData = new FormData();
formData.append(`plant_id`, bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.plant_id);
formData.append(`media_type`, bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.media_type);
if(bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.label !== undefined && bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.label !== null) {
 formData.append(`label`, bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.label);
 }
if(bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.tags !== undefined && bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.tags !== null) {
 formData.append(`tags`, bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.tags);
 }
formData.append(`file`, bodyCreateMediaAttachmentApiMediaMediaAttachmentsPost.file);

  const res = await fetch(getCreateMediaAttachmentApiMediaMediaAttachmentsPostUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createMediaAttachmentApiMediaMediaAttachmentsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createMediaAttachmentApiMediaMediaAttachmentsPostResponse
}



export type getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse200 = {
  data: unknown
  status: 200
}

export type getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponseSuccess = (getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse200) & {
  headers: Headers;
};
export type getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponseError = (getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse422) & {
  headers: Headers;
};

export type getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse = (getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponseSuccess | getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponseError)

export const getGetMediaAttachmentApiMediaMediaAttachmentsMediaIdGetUrl = (mediaId: number,) => {




  return `/api/media/media-attachments/${mediaId}`
}

/**
 * Get media attachment by ID.
 * @summary Get Media Attachment
 */
export const getMediaAttachmentApiMediaMediaAttachmentsMediaIdGet = async (mediaId: number, options?: RequestInit): Promise<getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse> => {

  const res = await fetch(getGetMediaAttachmentApiMediaMediaAttachmentsMediaIdGetUrl(mediaId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMediaAttachmentApiMediaMediaAttachmentsMediaIdGetResponse
}



export type updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse200 = {
  data: unknown
  status: 200
}

export type updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponseSuccess = (updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse200) & {
  headers: Headers;
};
export type updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponseError = (updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse422) & {
  headers: Headers;
};

export type updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse = (updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponseSuccess | updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponseError)

export const getUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutUrl = (mediaId: number,) => {




  return `/api/media/media-attachments/${mediaId}`
}

/**
 * Update media attachment metadata.
 * @summary Update Media Attachment
 */
export const updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut = async (mediaId: number,
    bodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut?: BodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut, options?: RequestInit): Promise<updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut?.label !== undefined && bodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut.label !== null) {
 formUrlEncoded.append(`label`, bodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut.label);
 }
if(bodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut?.tags !== undefined && bodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut.tags !== null) {
 formUrlEncoded.append(`tags`, bodyUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPut.tags);
 }

  const res = await fetch(getUpdateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutUrl(mediaId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateMediaAttachmentApiMediaMediaAttachmentsMediaIdPutResponse
}



export type deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse200 = {
  data: unknown
  status: 200
}

export type deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponseSuccess = (deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponseError = (deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse = (deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponseSuccess | deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponseError)

export const getDeleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteUrl = (mediaId: number,) => {




  return `/api/media/media-attachments/${mediaId}`
}

/**
 * Delete media attachment.
 * @summary Delete Media Attachment
 */
export const deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDelete = async (mediaId: number, options?: RequestInit): Promise<deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse> => {

  const res = await fetch(getDeleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteUrl(mediaId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteMediaAttachmentApiMediaMediaAttachmentsMediaIdDeleteResponse
}



export type getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse200 = {
  data: unknown
  status: 200
}

export type getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponseSuccess = (getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse200) & {
  headers: Headers;
};
export type getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponseError = (getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse422) & {
  headers: Headers;
};

export type getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse = (getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponseSuccess | getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponseError)

export const getGetMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetUrl = (plantId: string,) => {




  return `/api/media/media-attachments/plant/${plantId}`
}

/**
 * Get all media attachments for a plant.
 * @summary Get Media Attachments By Plant
 */
export const getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGet = async (plantId: string, options?: RequestInit): Promise<getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse> => {

  const res = await fetch(getGetMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetUrl(plantId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMediaAttachmentsByPlantApiMediaMediaAttachmentsPlantPlantIdGetResponse
}



export type getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse200 = {
  data: unknown
  status: 200
}

export type getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponseSuccess = (getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse200) & {
  headers: Headers;
};
export type getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponseError = (getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse422) & {
  headers: Headers;
};

export type getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse = (getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponseSuccess | getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponseError)

export const getGetMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetUrl = (mediaId: number,) => {




  return `/api/media/media-attachments/${mediaId}/url`
}

/**
 * Get presigned URL for media attachment.
 * @summary Get Media Attachment Url
 */
export const getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGet = async (mediaId: number,
    bodyGetMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGet?: BodyGetMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGet, options?: RequestInit): Promise<getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyGetMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGet?.expiration !== undefined) {
 formUrlEncoded.append(`expiration`, bodyGetMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGet.expiration.toString())
 }

  const res = await fetch(getGetMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetUrl(mediaId),
  {
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMediaAttachmentUrlApiMediaMediaAttachmentsMediaIdUrlGetResponse
}
