"""Initial migration

Revision ID: 72fff22905dd
Revises: 
Create Date: 2026-05-19 21:31:35.050025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fff22905dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genera',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('variety_name', sa.String(length=100), nullable=False),
    sa.Column('latin_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_packets',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('variety_name', sa.String(length=100), nullable=False),
    sa.Column('latin_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('days_to_maturity', sa.String(length=20), nullable=True),
    sa.Column('germination_time', sa.String(length=20), nullable=True),
    sa.Column('planting_depth', sa.String(length=20), nullable=True),
    sa.Column('spacing', sa.String(length=20), nullable=True),
    sa.Column('sun_requirements', sa.String(length=50), nullable=True),
    sa.Column('indoor_start_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('variety_name', sa.String(length=100), nullable=False),
    sa.Column('latin_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('days_to_maturity', sa.String(length=20), nullable=True),
    sa.Column('germination_time', sa.String(length=20), nullable=True),
    sa.Column('planting_depth', sa.String(length=20), nullable=True),
    sa.Column('spacing', sa.String(length=20), nullable=True),
    sa.Column('sun_requirements', sa.String(length=50), nullable=True),
    sa.Column('indoor_start_time', sa.String(length=50), nullable=True),
    sa.Column('planting_date', sa.String(length=10), nullable=False),
    sa.Column('seed_packet_id', sa.String(length=10), nullable=True),
    sa.Column('genus_id', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genus_id'], ['genera.id'], ),
    sa.ForeignKeyConstraint(['seed_packet_id'], ['seed_packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('amount_ml', sa.Integer(), nullable=True),
    sa.Column('fertilizer_type', sa.String(length=50), nullable=True),
    sa.Column('fertilizer_strength', sa.String(length=20), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(event_type != 'humidity') OR (level >= 1 AND level <= 10)", name='check_humidity_level'),
    sa.CheckConstraint("(event_type = 'humidity' AND level IS NOT NULL) OR (event_type = 'water' AND amount_ml IS NOT NULL) OR (event_type = 'fertilizer' AND fertilizer_type IS NOT NULL AND fertilizer_strength IS NOT NULL) OR (event_type = 'note' AND text IS NOT NULL)", name='check_event_type_fields'),
    sa.CheckConstraint("event_type IN ('humidity', 'water', 'fertilizer', 'note')", name='check_event_type'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_log_entries')
    op.drop_table('plants')
    op.drop_table('seed_packets')
    op.drop_table('genera')
    # ### end Alembic commands ###
